spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

  spring:
    jpa:
      hibernate:
        ddl-auto: none
