version: '3.8'

services:
  attendance-db:
    container_name: attendance-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'attendance_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - attendance-db-data:/var/lib/mysql
    networks:
      - attendance-tracker-net

  attendance-tracker:
    container_name: attendance-tracker
    image: attendance-tracker:latest
    environment:
      DB_URL: jdbc:mysql://attendance-db:3306/attendance_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USERNAME: admin
      DB_PASSWORD: password
      DB_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      - attendance-db
    ports:
      - "8081:8081"
    networks:
      - attendance-tracker-net

  qr-scanner:
    container_name: qr-scanner
    image: qr-code-scanner:latest
    environment:
      BACKEND_API_URL: http://attendance-tracker:8080
    ports:
      - "80:80"
    networks:
      - attendance-tracker-net

networks:
  attendance-tracker-net:
    driver: bridge

volumes:
  attendance-db-data: { }
